# Generated by Django 4.1.5 on 2023-01-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classes',
            new_name='Class',
        ),
    ]
