# Generated by Django 4.1.5 on 2023-01-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_reservation', '0002_rename_classes_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='ordinal',
        ),
    ]
